service: product-service
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  httpApi:
    cors: true

package:
  exclude:
    - ./**
  include:
    - products.json
    - package.json
  individually: true

functions:
  getProductsList:
    handler: getProductsList-dist.handler
    package:
      include:
        - getProductsList-dist.js
    events:
      - httpApi:
          path: /products
          method: get
  getProductsById:
    handler: getProductsById-dist.handler
    package:
      include:
        - getProductsById-dist.js
    events:
      - httpApi:
          path: /products/{productId}
          method: get
