openapi: 3.0.3

info:
  title: Product Service
  version: 1.0.11

servers:
  - url: https://0lwwwphm2k.execute-api.us-east-1.amazonaws.com

tags:
  - name: shop
    description: Products

paths:
  /products:
    get:
      tags:
        - shop
      summary: Get product list
      description: Returns a product list
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Product'

  /products/{productId}:
    get:
      tags:
        - shop
      summary: Get product by Id
      description: Returns a single product
      parameters:
        - name: productId
          in: path
          description: ID of product to return
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product' 
        '404':
          description: Product not found

components:
  schemas:
    Product:
      type: object
      properties:
        id:
          type: string
          format: uuid
        title:
          type: string
          description: Product name
        description:
          type: string
          description: Product description
        count:
          type: integer
          format: int64
        price:
          type: integer
          format: int64
